import 'package:flutter/material.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../../core/utils/ui_utils.dart';
import '../../../domain/entities/folder_entity.dart';
import '../../providers/providers.dart';

part 'folder_management_view_model.g.dart';

/// FolderManagement ViewModel
@riverpod
class FolderManagementViewModel extends _$FolderManagementViewModel {
  @override
  void build() {
    // No initial state needed
  }

  /// 폴더 순서 재정렬
  Future<void> reorderFolders(
    List<FolderEntity> folders,
    int oldIndex,
    int newIndex,
  ) async {
    if (oldIndex < newIndex) {
      newIndex -= 1;
    }

    final movedFolder = folders[oldIndex];
    final reorderedFolders = List<FolderEntity>.from(folders);
    reorderedFolders.removeAt(oldIndex);
    reorderedFolders.insert(newIndex, movedFolder);

    // Update order for all affected folders
    for (int i = 0; i < reorderedFolders.length; i++) {
      final folder = reorderedFolders[i];
      if (folder.order != i) {
        final updatedFolder = FolderEntity(
          id: folder.id,
          name: folder.name,
          color: folder.color,
          order: i,
        );
        await ref.read(updateFolderUseCaseProvider)(updatedFolder);
      }
    }
  }

  /// 폴더 삭제
  Future<void> deleteFolder(BuildContext context, FolderEntity folder) async {
    final confirmed = await UiUtils.showDeleteConfirmationDialog(
      context,
      title: '폴더 삭제',
      message: '${folder.name} 폴더를 삭제하시겠습니까?\n이 폴더의 할일들은 "전체"로 이동됩니다.',
    );

    if (confirmed) {
      try {
        await ref.read(deleteFolderUseCaseProvider)(folder.id);
        if (context.mounted) {
          UiUtils.showSuccessSnackBar(context, '폴더가 삭제되었습니다');
        }
      } catch (e) {
        if (context.mounted) {
          UiUtils.showErrorSnackBar(context, '오류가 발생했습니다: $e');
        }
      }
    }
  }

  /// 폴더 추가
  Future<void> addFolder(
    BuildContext context,
    String name,
    Color color,
    int order,
  ) async {
    try {
      final newFolder = FolderEntity(
        id: 0, // Will be auto-generated by database
        name: name,
        color: color.toARGB32(),
        order: order,
      );
      await ref.read(addFolderUseCaseProvider)(newFolder);

      if (context.mounted) {
        UiUtils.showSuccessSnackBar(context, '폴더가 추가되었습니다');
      }
    } catch (e) {
      if (context.mounted) {
        UiUtils.showErrorSnackBar(context, '오류가 발생했습니다: $e');
      }
    }
  }

  /// 폴더 수정
  Future<void> updateFolder(BuildContext context, FolderEntity folder) async {
    try {
      await ref.read(updateFolderUseCaseProvider)(folder);

      if (context.mounted) {
        UiUtils.showSuccessSnackBar(context, '폴더가 수정되었습니다');
      }
    } catch (e) {
      if (context.mounted) {
        UiUtils.showErrorSnackBar(context, '오류가 발생했습니다: $e');
      }
    }
  }
}
